### ISSUE TITLE
doesn't run on xinu

### ISSUE THREAD

**Issue by Bardiches** [BenLubar/df-ai#27]
see title

**Comment by BenLubar** [comment]
If you can get Dwarf Fortress to run on MIPS-based routers, I'm sure DFHack for MIPS-based routers is right around the corner!

**Comment by Bardiches** [comment]
hi i'm experiencing the same issue that @bardiches is

**Comment by Bardiches** [comment]
@BenLubar can you help both @bardiches and i seem to be having this issue

**Comment by Bardiches** [comment]
i tried npm install but it didn't work?

**Comment by Bardiches** [comment]
here is the issue i'm having http://imgur.com/a/5EGPO

**Comment by Bardiches** [comment]
@BenLubar can you please reopen this
it seems like @bardiches, @bardiches, @bardiches and i are all having the issue

**Comment by Bardiches** [comment]
hello? can you please help @bardiches, @bardiches, @bardiches, @bardiches, and i

**Comment by Bardiches** [comment]
i tried uninstalling games for windows but it didn't work, can someone help

**Comment by BenLubar** [comment]
@Bardiches you're running Games for Windows Live on a MIPS-based router?

**Comment by Bardiches** [comment]
not anymore??

**Comment by Bardiches** [comment]
@torvalds can you help?

**Comment by Bardiches** [comment]
Hi, I don't think this is supported yet? Can I have help? @BenLubar
