### ISSUE TITLE
Build df-ai for os x fails

### ISSUE THREAD

**Issue by sv-esk** [BenLubar/df-ai#3]
On os x gcc 4.5 is being used to [compile dfhack.](https://dfhack.readthedocs.org/en/stable/docs/Compile.html#mac-os-x)
Build fails with error "nullptr was not declared in ths scope. " because support for nullptr was added in GCC 4.6.0
DFHack itself avoids this fail by declaring:
>#ifndef HAVE_NULLPTR
>#define nullptr 0L
>#endif

**Comment by BenLubar** [comment]
@sv-esk does it compile now on OS X?

**Comment by sv-esk** [comment]
yes
