### ISSUE TITLE
Lockstep enabled prevents trade

### ISSUE THREAD

**Issue by mattregul** [BenLubar/df-ai#34]
DF & AI will just wait at the trade window until `ai disable lockstep` is preformed

**Comment by BenLubar** [comment]
Just so I'm sure I'm checking the right version, what does `ai version` say?

**Comment by mattregul** [comment]
Dwarf Fortress 0.43.05
  Windows 64-bit
df-ai 0.43.05-r2-54-ged61dab4
  code ed61dab468ef93c174a9bc3131c5fcf6bc5aa15e
DFHack 0.43.05-r2-48-g0ee421a9
  library 0ee421a9d40881a05aa5b382637148bdbe66ecb9
  structures 3322beb2e7f4b28ff8e573e9bec738c77026b8e9

**Comment by BenLubar** [comment]
Hmm, do you have any `tweak` commands in your `dfhack.init`? If possible, could you post your `dfhack.init` here?

**Comment by mattregul** [comment]
dfhack.init - https://gist.github.com/mattregul/3db77f1d815496bafc675abb788d7113#file-dfhack-init
my launcher - https://gist.github.com/mattregul/3db77f1d815496bafc675abb788d7113#gistcomment-2240134

**Comment by mattregul** [comment]
I do have this in my `onMapLoad_PeridexisErrant.init`
`repeat -time 1 -timeUnits months -command [ quicksave ] -name autosave`
Quicksaving every season to help recover from crashes

**Comment by BenLubar** [comment]
I wasn't able to reproduce a freeze when trading with lockstep enabled, but I did notice that the default `onLoad.init-example` that comes with DFHack causes some dialogue boxes to appear when dwarves are thirsty or stuck in trees. Are there any messages in the DFHack console related to an unexpected viewscreen or a pause of some kind?

**Comment by mattregul** [comment]
Two items:
1.  I updated to the latest version of df-ai, now I don't seem to be hanging on trade now.  Either its fixed, or its intermittent.   Maybe move the bug to a "monitoring" state? 
2.  Unsure, as I found the "thirsty" dialog annoying, so I removed the command for onLoad after the first time seeing it.

**Comment by dexofan23** [comment]
All works fine on latest builds with enabled lockstep
