### ISSUE TITLE
warn-starving, warn-stuck-trees, x for additional options

### ISSUE THREAD

**Issue by neoice** [BenLubar/df-ai#37]
I was experiencing game pauses due to `warn-starving` and `warn-stuck-trees`. I removed those files (lulz) and then began experiencing pauses with `x for additional options`.

this is with 0.43.05-r3 from the releases page. I've successfully run older versions of `df-ai` without these issues, but I want the new features :P

**Comment by lethosor** [comment]
What "x for additional options" are you referring to? Something in the stocks screen?

**Comment by BenLubar** [comment]
@lethosor is there some API I can use to determine whether a DFHack viewscreen was created by a user action or by code that was not directly triggered by the user?

**Comment by lethosor** [comment]
I think the only way you could do something like that right now would be in a state change handler (e.g. detecting when two screens show up within a frame of each other). I'm not sure about the warning scripts (warn-stuck-trees doesn't create a screen, though).

**Comment by neoice** [comment]
here's an example of the plugins being broken (I'll admit that I broke them. I can fix them to repro the **original** issue.

![screenshot_2017-12-11_11-07-27](https://user-images.githubusercontent.com/71924/33848765-91b30f26-de63-11e7-9f2f-21108a42149c.png)

give me a few minutes to get the other warninig.

**Comment by neoice** [comment]
> DFHack viewscreen

that is probably exactly what happens. I think the "stuck-trees" and "warn-starving" both resulted in menu screens that required human interaction to resolve.

**Comment by neoice** [comment]
> What "x for additional options" are you referring to? Something in the stocks screen?

this pops up sometimes and the game cannot continue until I clear it by pressing `ESC`

![screenshot_2017-12-11_11-33-12](https://user-images.githubusercontent.com/71924/33849957-20ad540e-de67-11e7-9b05-3da11f3b1a38.png)

**Comment by lethosor** [comment]
Oh, that is from the stocks screen, but df-ai must be going through that screen quickly enough to cause it to show up too late.

`gui/extended-status disable` should disable that.

**Comment by neoice** [comment]
this is the original "menu screen lock" that caused me to delete the `warn-*` plugins mentioned above.

![Uploading Screenshot_2017-12-12_08-22-26.png…]()

**Comment by neoice** [comment]
this is the original "menu screen lock" that caused me to delete the warn-* plugins mentioned above.

![screenshot_2017-12-12_08-22-26](https://user-images.githubusercontent.com/71924/33895616-bf8e3134-df15-11e7-8a0d-39aca22781f6.png)

**Comment by seutje** [comment]
try `repeat -cancel warn-starve`
