### ISSUE TITLE
0.44.05 version.

### ISSUE THREAD

**Issue by dotterian** [BenLubar/df-ai#38]
Since now there's there's alpha of DFHack for DF 0.44.05, are there any plans on upgradding DF-AI?
I've tried current version and it haven't even loaded properly.
Maybe it just need recompiling with dfhack-0.44.05 libraries, but I'm not the one who can do such things.

**Comment by lethosor** [comment]
Try https://buildmaster.local.lubar.me/applications/2/builds/build?releaseNumber=dfhack-0.44.05-alpha1&buildNumber=180114000

Ben has a release drafted for 0.44.xx, which makes me think he'll put one up here when DFHack becomes "stable" (which it essentially is).

**Comment by dotterian** [comment]
Thank you. This version woks like a charm.
