### ISSUE TITLE
request: camera optimization

### ISSUE THREAD

**Issue by alishahb** [BenLubar/df-ai#4]
Would be great if this can be implemented:

1) option to disable camera following completely
2) optimize camera to not move screen view on each drafw movement, but only when dwarf on the edge of viewable box (i.e. 10 tiles to the edge) or moved to other z-floor, as it hard to watch when camera moves too often

Thanks!

**Comment by BenLubar** [comment]
1) This has been implemented and is ready for the next release.
2) The AI only switches who is being followed. The actual following is done by Dwarf Fortress.

**Comment by alishahb** [comment]
got it, thanks will wait release than :)

**Comment by alishahb** [comment]
is there any planned date or ~ when new release will be available?

**Comment by BenLubar** [comment]
Since DF 0.43.01 came out today, the next release of df-ai will be whenever DFHack is updated.

**Comment by alishahb** [comment]
got it, thanks!
