### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by Unesty** [BenLubar/df-ai#40]
[DFHack]# enable df-ai
AI: ?????-??-??:???? choosing "New World"
AI: ?????-??-??:???? leaving world gen disclaimer
AI: ?????-??-??:???? choosing "Generate World"
Could not load script: onLoad.init-example
AI: removed onupdate
[DFHack]# 

/home/unesty/.dwarffortress/dfhack: line 68: 15106 Segmentation fault      (core dumped) setarch "$setarch_arch" -R env LD_PRELOAD="$PRELOAD_LIB" ./libs/Dwarf_Fortress "$@"

**Comment by BenLubar** [comment]
@Unesty Do you have the core dump? (You can enable writing one by running `ulimit -c unlimited` before running DFHack.)

Is there a specific sequence of actions that causes this to happen?

**Comment by Unesty** [comment]
@BenLubar core dump [(https://github.com/Unesty/MyProject5/blob/master/core.1929)]

**Comment by Unesty** [comment]
entity_default.txt and creature_standard.txt was modified

**Comment by BenLubar** [comment]
Where did you download DFHack from? The core dump doesn't seem to match any version of 0.44.05-r1 that I can find.

**Comment by Unesty** [comment]
From https://github.com/DFHack/dfhack

**Comment by BenLubar** [comment]
I'm going to close this assuming it was one of the crash bugs I fixed since 0.44.12-r1. If it's not, feel free to re-open this issue or file a new one.
