### ISSUE TITLE
spamming "00250-01-24:0854 [ERROR] viewscreen when queueing manager job is viewscreen_jobmanagementst, not viewscreen_createquotast"

### ISSUE THREAD

**Issue by neoice** [BenLubar/df-ai#43]
brand new fortress, latest version of everything.

I **think** it's trying to create jobs for which there are no materials yet. I saw a handful of successful jobs get created after the first mining was completed. example:

```
00250-01-16:0153 [ERROR] viewscreen when queueing manager job is viewscreen_dwarfmodest, not viewscreen_createquotast
00250-01-16:0154 add_manager_order(1) Construct rock Floodgate
00250-01-16:0168 [ERROR] viewscreen when queueing manager job is viewscreen_jobmanagementst, not viewscreen_createquotast
00250-01-16:0176 [ERROR] viewscreen when queueing manager job is viewscreen_jobmanagementst, not viewscreen_createquotast
00250-01-16:0193 [ERROR] viewscreen when queueing manager job is viewscreen_dwarfmodest, not viewscreen_createquotast
00250-01-16:0194 add_manager_order(6) Construct rock Door
00250-01-16:0208 [ERROR] viewscreen when queueing manager job is viewscreen_jobmanagementst, not viewscreen_createquotast
```

**Comment by BenLubar** [comment]
Is lockstep enabled or disabled?

**Comment by neoice** [comment]
I am using the default settings, so... maybe? you tell me! :joy:

**Comment by neoice** [comment]
switched to `true`... got worse?

game hung on the "Type in parts of the name....." screen.

`ESC to abort` fails. game seems entirely hung.

`disable df-ai` results in:

```
Disabling lockstep mode. df-ai will deactivate when lockstep mode has exited.
Could not disable plugin: df-ai
```

game is still totally hung, not responding to `ESC` key.

`enable df-ai` appears to hang `dfhack`. not responding to `ctrl - c`

I think that's the best explanation I can provide.

**Comment by neoice** [comment]
`./libs/Dwarf_Fortress` had low CPU usage during this time. did not respond to standard `kill`, required `kill -9`.

**Comment by BenLubar** [comment]
I wonder if GCC is getting confused by the workaround I had to do for a DFHack structures bug here:

https://github.com/BenLubar/df-ai/blob/ec8d07828be6a27cfc3cbef1ac4cb01f6f474e8a/stocks_manager.cpp#L227-L233

**Comment by neoice** [comment]
currently running:

```
% md5sum df_linux/hack/plugins/df-ai.plug.so 
6973986a6f10d781156ab37804000620  df_linux/hack/plugins/df-ai.plug.so
```

tried the gcc4.8 version:
```
% md5sum df-ai.plug.so 
b793833331852120d28c593128b77fad  df-ai.plug.so
```

issue persists.

**Comment by BenLubar** [comment]
I have a build going here: https://buildmaster.local.lubar.me/executions/execution-in-progress?executionId=67764

When it finishes, try the `df-ai.plug.so` from either `Linux64` or `Linux64-4.8` and tell me if the bug is fixed. (You don't have to try both.)

**Comment by neoice** [comment]
```
% md5sum df_linux/hack/plugins/df-ai.plug.so 
076f219a7adf7656e009fc1603b6e688  df_linux/hack/plugins/df-ai.plug.so
```

still there.

are you able to reproduce this yourself? is it potentially the save data itself?

could it be the fact that I'm living on the very bleeding edge of Linux? (I also have a Gentoo install I can test on, although not until much later today.)

```
% uname -a
Linux zion 4.16.0-rc2-next-20180221+neoice #5 SMP Wed Feb 21 04:07:37 PST 2018 x86_64 GNU/Linux
% cat /etc/debian_version  
buster/sid
```

**Comment by BenLubar** [comment]
Alright, with a structure change in DFHack, this bug has been fixed as far as I can tell. Here's a build of the fixed version: https://buildmaster.local.lubar.me/applications/2/builds/build?releaseNumber=dfhack-0.44.05-r2&buildNumber=180222003
