### ISSUE TITLE
Missing Software License

### ISSUE THREAD

**Issue by amartyn1996** [BenLubar/df-ai#44]
If you want other people to be allowed to copy, modify, and redistribute their own versions of this project you need a permissive license. Without it, normal copyright applies.

I would recommend the MIT license as it is simple and nonrestrictive.

If you would like to know more, you can read this short article on software licensing: https://www.techsoup.org/support/articles-and-how-tos/making-sense-of-software-licensing

This website gives a quick rundown on a few common open source licenses: https://choosealicense.com/

I hope this helps :)

**Comment by BenLubar** [comment]
https://github.com/DFHack/dfhack/blob/master/LICENSE.rst

As a DFHack plugin, df-ai is licensed under the ZLib license.
