### ISSUE TITLE
Announcements awaiting interaction (Enter key)

### ISSUE THREAD

**Issue by mattregul** [BenLubar/df-ai#49]
Some (all?) announcements aren't being closed, awaiting the user to press "Enter"

**Eamples:**
Here are two examples I noticed on my last run, awaiting the "Enter" key
- _xyz_ has assumed the position of expedition leader of _abc_
- _dwarf_ or _animal_ is thirsty or starving

**Version Info:**
- DF-AI `0.44.12-r1` from [7/17/18 Buildmaster](https://buildmaster.local.lubar.me/applications/2/builds/build?releaseNumber=0.0.0&buildNumber=180717001)
- DFHack `0.44.12-r1-0-gc2a64b35`

**Extra:**
This issues was also mentioned in [issue 48](https://github.com/BenLubar/df-ai/issues/48)

**Comment by lethosor** [comment]
The first one isn't a DFHack announcement. Also, I'm not sure why you would duplicate an open issue.

**Comment by mattregul** [comment]
Update - Removed "DFHack" from name and description. :)

**Comment by mattregul** [comment]
_Similar to [#37 - warn-starving, warn-stuck-trees, x for additional options](https://github.com/BenLubar/df-ai/issues/37#issuecomment-351103796)_

**Comment by BenLubar** [comment]
For future reference, the `ai version` command should give you a pretty complete set of version information.

**Comment by mattregul** [comment]
I tied using that yesterday, but nothing was showing up in the console. 🤔

**Comment by BenLubar** [comment]
Is this happening when the AI is performing a specific action? Is there a copy of the pause message in the AI's log?

**Comment by mattregul** [comment]
Since I've switched to using the latest build master releases, I've not encountered this bug since reporting it
