### ISSUE TITLE
allow disabling autolabor and update_nobles

### ISSUE THREAD

**Issue by hejgustav** [BenLubar/df-ai#5]
I just wanted to ask if it'd be possible to make a version where it didn't do the labors and nobles but still did the the other things 'cause i like doing those things but not so much the other stuff.

I'm new to github so sorry if this isn't the right place to ask.

**Comment by BenLubar** [comment]
I'm busy right now, but I'll add a configuration option later.

Note to self:
https://github.com/BenLubar/df-ai/blob/0.43.03-alpha1/ai.cpp#L279
https://github.com/BenLubar/df-ai/blob/0.43.03-alpha1/population.cpp#L1078

**Comment by hejgustav** [comment]
Thank you so much for continuing to work on this and taking time off to do my dumb request. (And changing my title to something a little less stupid)
