### ISSUE TITLE
Military squads aren't being refilled?

### ISSUE THREAD

**Issue by mattregul** [BenLubar/df-ai#55]
**Describe the bug**
Just noticed in my current game of 39 years, with 231 citizens, has pretty much no military presents.
- **Captain of the Guard:** None
- **Squad 1** - 2 dwarves (squad position 1 & 3)
- **Squad 2** - No units
- 120 available candidates

**What happened**
DF-AI isn't refilling squads?

**Expected behavior**
With a population of 239 _(120 candidates)_, I was expecting several full squads of dwarven killing machines

**Visual reference**
## Squads 
![image](https://user-images.githubusercontent.com/8008527/43670690-012eb4ba-975d-11e8-8ea3-c2100c47a04c.png)
![image](https://user-images.githubusercontent.com/8008527/43670877-2cbb0370-975f-11e8-932d-9fa8f6c68207.png)

## Citizen Summary
![image](https://user-images.githubusercontent.com/8008527/43670932-f9baa9f2-975f-11e8-8c53-73690171f30e.png)

## Citizens - Page 1
![image](https://user-images.githubusercontent.com/8008527/43670731-7cdd5ce2-975d-11e8-8486-5a96ee43d49e.png)
## Citizens - Page 2
![image](https://user-images.githubusercontent.com/8008527/43670736-8f2f22ae-975d-11e8-9396-3364bbf0c5c5.png)
## Citizens - Page 3
![image](https://user-images.githubusercontent.com/8008527/43670742-a17b586a-975d-11e8-820f-69f2ee3cb8cd.png)
## Citizens - Page 4
![image](https://user-images.githubusercontent.com/8008527/43670750-b141f9d4-975d-11e8-86ae-fb3baee4e0c8.png)
## Citizens - Page 5
![image](https://user-images.githubusercontent.com/8008527/43670756-bcd4173c-975d-11e8-9c41-eb83dcb82a0d.png)
## Weapons
![image](https://user-images.githubusercontent.com/8008527/43670952-34adb0b8-9760-11e8-8a9c-81d19a27da82.png)
## Armor
![image](https://user-images.githubusercontent.com/8008527/43670962-4d50ecb6-9760-11e8-83d7-8d4589107eef.png)

**ai version:**
```
Dwarf Fortress 0.44.12
  Windows 64-bit
df-ai 0.44.12-r1-update1-5-g9c2c4a64 (Build ID: df-ai-pre-0.44.12-r1-180801001)
  code 9c2c4a648f508366ca0d49f5445c5fbb5f9503f3
DFHack 0.44.12-r1-0-gc2a64b35 (Build ID: df-ai-pre-0.44.12-r1-180801001)
  library c2a64b3573abbee549761f5c1c2626eec7a6e81c
  structures 23500e4e9bd1885365d0a2ef1746c321c1dd5094```

**Comment by mattregul** [comment]
![image](https://user-images.githubusercontent.com/8008527/43670877-2cbb0370-975f-11e8-932d-9fa8f6c68207.png)

**Comment by mattregul** [comment]
Ahh interesting.
- 1 copper pick, in inventory
- 2 copper battle axes, in inventory
- 1 copper battle axe, forbidden

**Comment by mattregul** [comment]
I'm actually fairly new to the game, I've been wanting to try it for years but never picked it up.  Your AI is what got me to download the game. I figured I'll let the AI do its thing and learn the game as we go... So, hopefully the above info is what you needed

**Comment by BenLubar** [comment]
Basically, the AI won't add anyone else to the military because it's worried about the military having all the axes/picks and none being left to actually gather materials.

I'm unsure of how to handle this. Maybe force new squad members to be ranged when this happens, since there aren't any ranged axes or picks?

**Comment by mattregul** [comment]
Hmm, perhaps I'm out of resources, as my dwarfs aren't really digging anymore.  Perhaps we need to stripmine until we have X-amount of resources in stock?

**Comment by mattregul** [comment]
No resources, no new picks

**Comment by mattregul** [comment]
Is the AI unable to filter melee weapons? Meaning, if there are swords, maces, etc... why won't the military use them?

**Comment by mattregul** [comment]
or perhaps the AI just tells the dwarf, hey... you are melee... go find a weapon... and that puts picks and axes at risk

**Comment by BenLubar** [comment]
The AI used to assign each squad's weapons individually, but it did that at squad creation, not when assigning new members to the squad.

Maybe it would be a good idea to keep allowing squads to have any weapon, but if a `Dig` or `ChopTree` job isn't able to be filled, whoever is holding the tool would be manually assigned a different weapon.

**Comment by mattregul** [comment]
🥇Nice, loaded up the same save, ai immediately created 11 squads, 105 soldiers!

**Comment by BenLubar** [comment]
If their highest weapon skill is lower than their wrestling skill, they show up as wrestlers. If you have a lot of them, that's probably because there aren't any weapons for them to train with.
