### ISSUE TITLE
Blueprint Overlapping

### ISSUE THREAD

**Issue by mattregul** [BenLubar/df-ai#56]
**Describe the bug**
Appears that rooms (and stockpiles) can overlap.  This may be due to multiple gaming sessions.  Always the same game & ai version, just multiple save/loads/`enable df-ai`'s

- **Example 1:**
   Overlapping didn't seem like much of an issue until I noticed that most of my fort was depressed and horrified, from constantly seeing bodies and bone refuse.

 - **Example 2:**
   Dwarves were trapped down in the mines, as a z-level of their mineshaft was removed for a new fortress room.  Noticed as I started seeing inaccessible item & dehydration/starvation messages.

**Expected behavior**
Prevent structure overlapping or at least ensure bodies and refuse stockpiles are enclosed.

**Visual reference**
- See top middle and bottom right
- I was attempting to wall off the bones at top middle before taking screenshot
- Also note the many blocks of stairways
![image](https://user-images.githubusercontent.com/8008527/43839071-31ba2c9a-9aeb-11e8-916a-845eece5e389.png)

**ai version:**
```
Dwarf Fortress 0.44.12
  Windows 64-bit
df-ai 0.44.12-r1-update1-6-gc32576d7 (Build ID: df-ai-pre-0.44.12-r1-180805000)
  code c32576d7b45f1336ad9f28272f6856655f80934e
DFHack 0.44.12-r1-0-gc2a64b35 (Build ID: df-ai-pre-0.44.12-r1-180805000)
  library c2a64b3573abbee549761f5c1c2626eec7a6e81c
  structures 23500e4e9bd1885365d0a2ef1746c321c1dd5094
```

**Comment by mattregul** [comment]
Does not seem to be related to multiple gaming sessions.  Seeing overlap with fresh embark.

**Comment by mattregul** [comment]
RIP - Poor fella was walled in
![image](https://user-images.githubusercontent.com/8008527/43854879-1fb95094-9b12-11e8-8934-4e0d3fac2265.png)

**Comment by BenLubar** [comment]
Ok, a few questions:

- Is the AI generating a new layout every time it loads a save? It shouldn't be.
- Do the room interiors overlap or is it just missing space for walls?
- Is there a file named `df-ai-plan.dat` in your save folder (`region#`)?
- Does the `df-ai-plan.dat` file increase significantly in size when you load and immediately save?

**Comment by mattregul** [comment]
1. Does not appear to be generating a new layout everytime, at least with my current save.
   - I'll do some more testing tonight/overnight
1. I originally thought interiors overlap, as seen below... but maybe it is just missing walls? Hmm
    ![image](https://user-images.githubusercontent.com/8008527/43863606-36715c14-9b2b-11e8-8d14-a8f233e71046.png)
   - I'll do some more testing tonight/overnight
1. Yes (`2.58 MB (2,707,456 bytes)`)
1. No, appears to stay the same.

**Comment by mattregul** [comment]
![image](https://user-images.githubusercontent.com/8008527/43901881-98fca2c2-9bb6-11e8-89bb-571cef349923.png)

**Comment by mattregul** [comment]
![image](https://user-images.githubusercontent.com/8008527/43901986-e57e564a-9bb6-11e8-8c38-5dfee90fdd14.png)

**Comment by mattregul** [comment]
Looking more like walls/outer edge of blueprints aren't being taken into account when deciding placement?

**Comment by mattregul** [comment]
![image](https://user-images.githubusercontent.com/8008527/43911739-35ff540e-9bce-11e8-8ac3-b4a31b919f4c.png)
Definitely looking like its just missing walls
