### ISSUE TITLE
Bedrooms facing opposite direction?

### ISSUE THREAD

**Issue by mattregul** [BenLubar/df-ai#57]
**Describe the bug**
Appears that in **_some_** instances, bedrooms can be queued with the entrance on the opposite side of the corridor.  
- There's already a northern-bedroom in use, so it's not _every_ northern instance that's flipped.
    (See screenshot 2) 

- The flipped bedrooms have the entrance on the right side, but others are on the left side.
    (See screenshot 3)

- Attached [df-ai.log](https://github.com/BenLubar/df-ai/files/2283564/df-ai.log) is for first screenshot

**Visual reference**
![image](https://user-images.githubusercontent.com/8008527/44040789-1a83c8ee-9eea-11e8-8988-47302301fd4b.png)

![image](https://user-images.githubusercontent.com/8008527/44040819-2e06c20e-9eea-11e8-94b8-cdd7aabb4208.png)

![image](https://user-images.githubusercontent.com/8008527/44041886-e32f1634-9eec-11e8-888a-74208326fef0.png)

**ai version:**
```
Dwarf Fortress 0.44.12
  Windows 64-bit
df-ai 0.44.12-r1-update1-8-g7b306e26 (Build ID: df-ai-pre-0.44.12-r1-180810000)
  code 7b306e2669d0c4fd933a73e360e5f9f0a7ba7ee6
DFHack 0.44.12-r1-0-gc2a64b35 (Build ID: df-ai-pre-0.44.12-r1-180810000)
  library c2a64b3573abbee549761f5c1c2626eec7a6e81c
  structures 23500e4e9bd1885365d0a2ef1746c321c1dd5094
```

**Additional context**
[df-ai.log](https://github.com/BenLubar/df-ai/files/2283564/df-ai.log) _(log is for first screenshot)_

**Comment by mattregul** [comment]
Manually digging, to open the rooms, allows the AI to continue making additional bedrooms.

**Comment by BenLubar** [comment]
It looks like the broken one in this screenshot is the `west_south` template.
