### ISSUE TITLE
Does this work with Masterwork?

### ISSUE THREAD

**Issue by GothThot** [BenLubar/df-ai#67]
I've tried using this with the latest version of Masterwork, but as soon as the AI initializes, the game crashes. Would this work at all with Masterwork, or should I stop trying? Here's the log file if it helps.
[df-ai-debug.log](https://github.com/BenLubar/df-ai/files/2921884/df-ai-debug.log)

**Comment by BenLubar** [comment]
Hmm, does Masterwork disable the starting-a-fortress text screen? I could add handling for that.

**Comment by lethosor** [comment]
I know in the past it has customized the text on that screen. I'd be surprised if it disables the screen entirely now.

**Comment by BenLubar** [comment]
Probably going to add a "dismiss textviewer, expecting it to go to this screen next" thing because there are other similar issues currently open.
