### ISSUE TITLE
AI Following creatures at very low levels 10-20min into game

### ISSUE THREAD

**Issue by sparton175** [BenLubar/df-ai#74]
**Describe the bug**

Early in the game the AI goes down the 100-200 and starts following all of the creatures, ends up neglecting the dwarfs causing the fortress to fail. This happens when there is a cave-in and you get the "screams from below" pop-up.

**What happened**
What did df-ai do that you didn't expect?

**Expected behavior**

**Visual reference**
If applicable, paste in a screenshot or a Twitch clip.

**ai version:**
```
Run the following command in the DFHack console and paste the output here (between the triple backticks).

    ai version

[DFHack]# ai version
Dwarf Fortress 0.47.04
  Windows 64-bit
df-ai 0.47.04-r1-0-gd06a8a8c
  code d06a8a8caeb05fcf55995b3d77a5828167f43907
DFHack 0.47.04-r1-0-g6bdbf5b0
  library 6bdbf5b0ddaa045a8fc6ff91e91dc30cb3d21e3f
  structures 0792fc0202fb6a04bfdaa262bc36a3b14c8581e5
[DFHack]#

```

**Additional context**
Anything else you'd like to add?

**If you have a df-ai-debug.log file, drag or paste the file into this issue.**

**Comment by BenLubar** [comment]
The camera position doesn't affect the AI's actions. Are you using custom raws or other plugins that might be manipulating terrain? If not, there's probably something misaligned in df-structures that's causing memory corruption.

Do you remember if the terrain was revealed? (That is, instead of the black void, all the underground dirt and rock tiles were visible.) I saw something similar to this when I was testing dfplex with @white-rabbit-dfplex, but we couldn't figure out how to reproduce it.

**Comment by sparton175** [comment]
I looked into the issue more, I don't use any additional mods but I notice that the AI is trying to fight creatures that are no longer on the map or cannot be reached. This ends up causing many dwarfs to die of thirst or hunger and the whole fortress falls apart. I will run another fortress and attach the history of what happens

**Comment by sparton175** [comment]
Deaths
In 264 on the 17th of Opal, Dumat Kuletkerl├«g drowned at the age of 130¾ in Limulamas.
In 265 on the 25th of Moonstone, Momuz Kosothkod died of thirst at the age of 57½ in Limulamas.
In 266 on the 9th of Slate, Dumat Kuletkerl├«g was laid to rest at the age of 132 in Limulamas.
In 266 on the 19th of Felsite, Soshosh Arakgenlath Bothonkor died in a collision after being attacked by Volalum in Limulamas.
In 266 on the 21st of Hematite, [unnamed male horse child] starved to death at only 92 days old in Limulamas.
In 266 on the 25th of Hematite, Kulet Besmartabar died of thirst at the age of 66¼ in Limulamas.
In 266 on the 19th of Limestone, Zulban Lalturkogan died of thirst at the age of 59 in Limulamas.
In 266 on the 27th of Limestone, Ral Aranineth was drained of blood by Sarvesh Avalrith Dumatromlam S├»sal at the age of 59 in Limulamas.
In 266 on the 3rd of Timber, Kulet Besmartabar was laid to rest at the age of 66¾ in Limulamas.
In 266 on the 27th of Moonstone, Rith Amostgamil was drained of blood by Sarvesh Avalrith Dumatromlam S├»sal at the age of 77¾ in Limulamas.
In 266 on the 2nd of Obsidian, Kib Tad├▓nul bled to death, killed by Vutok Cogugosh in Limulamas.
In 266 on the 2nd of Obsidian, Vutok Cogugosh bled to death with a copper battle axe, killed by Kadol Gesisunib at the age of 20¾ in Limulamas.
In 267 on the 11th of Slate, ├¿zum Idenbavast was slain with a silver mace by ├¿rith Kodorkeskal at the age of 6¾ in Limulamas.
In 267 on the 17th of Slate, Rith Amostgamil was laid to rest at the age of 78 in Limulamas.
In 267 on the 3rd of Hematite, ├¡lime Alethicera was slain with a silver short sword by Zulban Ragst├ókud at the age of 125¾ in Limulamas.
In 267 on the 28th of Hematite, ├¿zum Kivishubal was drained of blood by Sarvesh Avalrith Dumatromlam S├»sal at the age of 87 in Limulamas.
In 267 on the 27th of Malachite, Ngesosp Zosputospas Remzuestrur was slain by ├┐onali Sanenefeceve Fiso in Limulamas.
In 267 on the 7th of Galena, ├┐onali Sanenefeceve Fiso was slain by Nanilene in Limulamas.
In 267 on the 15th of Galena, Tobul Lolorud bled to death, killed by Vucar Vutokasol at the age of 165½ in Limulamas.
In 267 on the 15th of Galena, Kol Obokkutam was slain with a steel battle axe by B├½mbul Tosidkir at the age of 52¾ in Limulamas.
In 267 on the 2nd of Limestone, Mestthos Litastcubor was slain with a copper scourge by Osnun Urarok at the age of 78¼ in Limulamas.
In 267 on the 2nd of Limestone, Ral Aranineth was laid to rest at the age of 60 in Limulamas.
In 267 on the 2nd of Limestone, ├»ngiz Vudtharkosoth was slain with a copper bow by Snamoz Snangspamo at the age of 75¾ in Limulamas.
In 267 on the 2nd of Limestone, Ustuth Enseboltar was slain with a copper scourge by Osnun Urarok at the age of 28 in Limulamas.
In 267 on the 2nd of Limestone, Snamoz Snangspamo was slain with a silver battle axe by Sigun Cerolker at the age of 217½ in Limulamas.
In 267 on the 2nd of Limestone, Osnun Urarok was slain by Sigun Cerolker at the age of 238¼ in Limulamas.
In 267 on the 2nd of Limestone, Snamoz Urabsong was slain with a silver battle axe by ├¿zum Etasinod in Limulamas.
In 267 on the 2nd of Sandstone, Zulban Ragst├ókud was drained of blood by Sarvesh Avalrith Dumatromlam S├»sal at the age of 90½ in Limulamas.
In 267 on the 7th of Moonstone, Kol Obokkutam was laid to rest at the age of 53¼ in Limulamas.
In 267 on the 8th of Opal, Urdim Keskad├┤l died of thirst at the age of 132¾ in Limulamas.
In 268 on the 2nd of Granite, Salore Eri├┐arofa was slain with a bismuth bronze battle axe by Ed├½m Imushf├┤ker at the age of 86½ in Limulamas.
In 268 on the 2nd of Granite, Niri Ovaceli was slain with a silver battle axe by Asmel Idarel at the age of 91¾ in Limulamas.
In 268 on the 2nd of Granite, Melbil Nomalrig├▓th was slain by Fela Leneforile at the age of 72½ in Limulamas.
In 268 on the 2nd of Granite, Vinena Conibodimati bled to death with a bismuth bronze battle axe, killed by Ed├½m Imushf├┤ker at the age of 46½ in Limulamas.
In 268 on the 2nd of Granite, Themiyi Laliwele bled to death with a silver battle axe, killed by Ilral Ralkeskal at the age of 53¼ in Limulamas.
In 268 on the 2nd of Granite, Tholtig Gis├½kmeng bled to death, killed by Fela Leneforile at the age of 93 in Limulamas.
In 268 on the 2nd of Granite, Zepave Mideb├¡queca bled to death, killed by Mafol Uristurr├»th at the age of 27¾ in Limulamas.
In 268 on the 2nd of Granite, Avafi Eminoimaza was slain with a silver war hammer by R├«sen Astt├ómol at the age of 116 in Limulamas.
In 268 on the 2nd of Granite, Lene Ofafamime was slain with a silver battle axe by Asmel Idarel at the age of 53 in Limulamas.
In 268 on the 2nd of Granite, Fela Leneforile was slain with a silver war hammer by R├«sen Astt├ómol at the age of 9½ in Limulamas.
In 268 on the 2nd of Granite, Salore Thilubithemi was slain with a silver battle axe by ├¿zum Etasinod at the age of 136 in Limulamas.
In 268 on the 3rd of Granite, Gica Erenaula was slain with a silver short sword by Momuz R├¼tharbomrek at the age of 121 in Limulamas.
In 268 on the 3rd of Granite, Lora Imepesareve was slain with Istbarmigrur Kabmishthem by Tobul Taronoddom at the age of 132 in Limulamas.
In 268 on the 3rd of Granite, Nine Eri├┐acovema was slain with Istbarmigrur Kabmishthem by Tobul Taronoddom at the age of 105 in Limulamas.
In 268 on the 3rd of Granite, Saba Fol├¡ale├┐a was slain with a silver mace by Deg├½l ├»ngizcud├»st at the age of 119 in Limulamas.
In 268 on the 3rd of Granite, [unnamed yak cow] was slain with a silver short sword by Ast Mogshumshem at the age of 21½ in Limulamas.
In 268 on the 3rd of Granite, Narena Thit├¡aya was slain with a silver war hammer by D├«shmab Cilobilrom at the age of 136 in Limulamas.
In 268 on the 4th of Granite, Etini Amayithema was slain with a silver battle axe by Minkot Udistlolok at the age of 53¾ in Limulamas.
In 268 on the 11th of Granite, Solon Un├ólal├Ñth bled to death, killed by Kadol Gesisunib in Limulamas.
In 268 on the 17th of Granite, ├¿zum Kivishubal was laid to rest at the age of 87¾ in Limulamas.
In 268 on the 10th of Slate, Ilral Ralkeskal died of thirst at the age of 63¼ in Limulamas.
In 268 on the 11th of Slate, Mafol Uristurr├»th succumbed to infection after being attacked by Mimale Thiluirecu at the age of 76¼ in Limulamas.
In 268 on the 12th of Slate, Kel Evonlibash died of thirst at the age of 58¾ in Limulamas.
In 268 on the 28th of Slate, Zefon Ulzestasmel died of thirst at the age of 61¾ in Limulamas.
In 268 on the 1st of Felsite, Udil B├╗nemkadol died of thirst at the age of 53 in Limulamas.
In 268 on the 3rd of Felsite, R├«sen Astt├ómol died of thirst at the age of 59 in Limulamas.
In 268 on the 3rd of Felsite, B├½mbul Tosidkir died of thirst at the age of 74¾ in Limulamas.
In 268 on the 7th of Felsite, Logem Asobbesmar died of thirst at the age of 56½ in Limulamas.
In 268 on the 23rd of Felsite, Ineth Sazirteling was slain with a steel crossbow by Rimtar Nishardes at the age of 56¾ in Limulamas.
In 268 on the 6th of Hematite, Th├«kut Kekath├╣shrir was slain by Obok Logembekar in Limulamas.
In 268 on the 8th of Hematite, Zas ├álilmeng died of thirst at the age of 52¼ in Limulamas.
In 268 on the 14th of Hematite, Tholtig Gis├½kmeng was laid to rest at the age of 93¼ in Limulamas.
In 268 on the 17th of Hematite, ├╣shrir Koganal├Ñth was drained of blood by Sarvesh Avalrith Dumatromlam S├»sal at the age of 70¼ in Limulamas.
In 268 on the 19th of Hematite, Leto Tethagicast was drained of blood by Sarvesh Avalrith Dumatromlam S├»sal at the age of 40½ in Limulamas.
In 268 on the 3rd of Malachite, Endok Tosidneth died of thirst at the age of 15 in Limulamas.
In 268 on the 19th of Malachite, Ilral Ralkeskal was laid to rest at the age of 63½ in Limulamas.
In 268 on the 9th of Galena, Mestthos Litastcubor was laid to rest at the age of 79¼ in Limulamas.
In 268 on the 10th of Galena, B├½mbul Tosidkir was laid to rest at the age of 75 in Limulamas.
In 268 on the 11th of Galena, Obok Logembekar died of thirst at the age of 72 in Limulamas.
In 268 on the 14th of Galena, Onget Thukkanvab├┤k died of thirst at the age of 67½ in Limulamas.
In 268 on the 23rd of Galena, Ber Zesast died of thirst at the age of 96½ in Limulamas.
In 268 on the 17th of Limestone, Dastot Usen├▓nul died of thirst at the age of 57¾ in Limulamas.
In 268 on the 8th of Sandstone, ├¿rith Kodorkeskal died of thirst at the age of 97½ in Limulamas.
In 268 on the 12th of Sandstone, Stukos Asobethab was slain by Rith Ostuknish at the age of 63 in Limulamas.
In 268 on the 12th of Sandstone, Mebzuth Kibegeb died of thirst at the age of 51½ in Limulamas.
In 268 on the 4th of Moonstone, Rith Ostuknish died of thirst at the age of 88½ in Limulamas.
In 268 on the 6th of Moonstone, Dod├│k Idsolon was slain with a silver mace by Dastot Istrathed├½m at the age of 54½ in Limulamas.
In 268 on the 6th of Moonstone, Tirist Sigunbardum was slain with a silver battle axe by Minkot Udistlolok at the age of 85½ in Limulamas.
In 268 on the 8th of Moonstone, Minkot Udistlolok suffocated, strangled by Ustuth Avuztatlosh at the age of 27¼ in Limulamas.
In 268 on the 14th of Moonstone, Ustuth Uremoltar died of thirst at the age of 76 in Limulamas.
In 268 on the 19th of Moonstone, Vutok Kuletvesh died of thirst at the age of 26¾ in Limulamas.
In 268 on the 18th of Opal, Onget Thukkanvab├┤k was laid to rest at the age of 68 in Limulamas.
In 268 on the 24th of Opal, Melbil Konosdogik was slain with Desorkib by Rimtar Likotum at the age of 81½ in Limulamas.
In 268 on the 4th of Obsidian, Iden Idensheced suffocated, strangled by Urdim Kordamzefon at the age of 76 in Limulamas.
In 268 on the 8th of Obsidian, Deg├½l ├»ngizcud├»st died of thirst at the age of 79½ in Limulamas.
In 268 on the 16th of Obsidian, Zefon Onol├Ñkum died of thirst at the age of 70¼ in Limulamas.
In 268 on the 21st of Obsidian, Urvad Lokumreg died of thirst at the age of 65¾ in Limulamas.
In 269 on the 2nd of Granite, Nomal Esismonom bled to death, killed by Athifi ├┐ivueri├┐a at the age of 60¾ in Limulamas.
In 269 on the 2nd of Granite, At├¡r Razesbesmar suffocated, strangled by Vafice Thiluyifa at the age of 56¼ in Limulamas.
In 269 on the 2nd of Granite, Vafice Thiluyifa was slain with a silver mace by Ustuth Avuztatlosh in Limulamas.
In 269 on the 2nd of Granite, Ed├½m Alnisdod├│k bled to death, killed by Athifi ├┐ivueri├┐a at the age of 24 in Limulamas.
In 269 on the 3rd of Granite, Athifi ├┐ivueri├┐a was slain with a steel battle axe by ├¿zum Etasinod at the age of 195¾ in Limulamas.
In 269 on the 3rd of Granite, Amoya Lolamathiyira was slain with a silver mace by Endok Kosothenshal at the age of 134 in Limulamas.
In 269 on the 3rd of Granite, Ale Thasalapama was slain with a silver short sword by Ubbul Kad├┤limesh at the age of 122¼ in Limulamas.
In 269 on the 4th of Granite, Ustuth Avuztatlosh suffocated, strangled by Epeve A├┐araatera at the age of 20 in Limulamas.
In 269 on the 4th of Granite, Kosoth Dod├│kat├«s bled to death, killed by Rath├¿ Moweemofe at the age of 84½ in Limulamas.
In 269 on the 4th of Granite, Rath├¿ Moweemofe was slain with a steel battle axe by ├¿zum Etasinod at the age of 11¾ in Limulamas.
In 269 on the 17th of Granite, [unnamed male horse] was slain by Gosterb├ósen Egom at the age of 9¼ in Limulamas.
In 269 on the 17th of Granite, Gosterb├ósen Egom bled to death with a silver mace, killed by Endok Kosothenshal in Limulamas.
In 269 on the 5th of Slate, Urdim Kordamzefon died of thirst at the age of 120 in Limulamas.
In 269 on the 6th of Slate, Deler Gamilbomrek died of thirst at the age of 50½ in Limulamas.
In 269 on the 12th of Slate, Kad├┤l Istbarm├╢rul was slain by ├¿zum Anrizducim at the age of 162¼ in Limulamas.
In 269 on the 22nd of Slate, Nil ├«tonvab├┤k died of thirst at the age of 67¼ in Limulamas.
In 269 on the 24th of Slate, Mafol San├íd├¿rith died of thirst at the age of 89½ in Limulamas.
In 269 on the 24th of Slate, Rimtar Likotum died of thirst at the age of 73 in Limulamas.
In 269 on the 24th of Slate, Kadol Gesisunib suffocated, strangled by ├¿zum Desorbomrek at the age of 80½ in Limulamas.
In 269 on the 25th of Slate, Vucar Vutokasol died of thirst at the age of 102½ in Limulamas.
In 269 on the 27th of Slate, Mestthos Zatamlogem died of thirst at the age of 60½ in Limulamas.
In 269 on the 27th of Slate, Amost Konostat suffocated, strangled by Ingish Ubbulst├ókud at the age of 68½ in Limulamas.
In 269 on the 1st of Felsite, Olin Lesastkikrost died of thirst at the age of 63¼ in Limulamas.
In 269 on the 2nd of Felsite, Vucar Vutokemgash died of thirst at the age of 78 in Limulamas.
In 269 on the 5th of Felsite, K├╗buk Zunt├«rkivish suffocated, strangled by Mist├¬m Shagogbomrek at the age of 88¾ in Limulamas.
In 269 on the 5th of Felsite, ├«ton Stuldeduk died of thirst at the age of 106½ in Limulamas.
In 269 on the 5th of Felsite, Mist├¬m Nokzamdod├│k died of thirst at the age of 80½ in Limulamas.
In 269 on the 6th of Felsite, Sarvesh Kikrostmasos died of thirst at the age of 121¼ in Limulamas.
In 269 on the 7th of Felsite, Dakost Silmist├¬m died of thirst at the age of 87 in Limulamas.
In 269 on the 8th of Felsite, Zunt├«r Athelmat died of thirst at the age of 20½ in Limulamas.
In 269 on the 8th of Felsite, Kogan Kelroldeth died of thirst at the age of 83¾ in Limulamas.
In 269 on the 18th of Felsite, Tun Vab├┤kzokun suffocated, strangled by Kol Limulkes at the age of 78¼ in Limulamas.
In 269 on the 22nd of Felsite, Ustuth Ometzefon died of thirst at the age of 66 in Limulamas.
Jobs

**Comment by lukebemish** [comment]
I have had this same issue. It seemed to always occur after collapse on the surface. Every tile on the map was revealed. I could not find any reason for the collapse on the surface, so I suspect that it was caused by df-ai. I got a "something on the surface has collapsed" message, the entire map was revealed, and the camera started following creatures in the underworld. I'll try it again in just a bit and see if I can figure out what, exactly, is collapsing on the surface, but the fact that the entire map was revealed is rather odd. I assume that this is why it began tracking the creatures; revealing the underworld caused them to appear.

It might be worth noting that I used df-ai to embark in an existing world, instead of using it to create a new one, though I'm not sure if this could have any effect. If I can reproduce it on this save but not any other, I'll send you the save.

**Comment by lukebemish** [comment]
Something else odd to note; when this happens, it seemed like the entire map was sort of "reset" to an earlier state, with blocks being filled in, including those already dug underground or trees already cut down. My guess is that this is what happened, with the map somehow being reset to embark and revealed, which caused some things (trees that had grown?) to collapse.

I could reproduce this on an existing save. I could reproduce it by letting df-ai create a new save from the main menu. It always happens some time within the first few seasons, but the timing isn't constant.

**Comment by lethosor** [comment]
Had you used `open-legends` in this save?

**Comment by lukebemish** [comment]
Yes - however, I always exited it using die and could reproduce it in another save where it hadn't been used.

**Comment by lukebemish** [comment]
This may not be a df-ai issue

I was just playing without df-ai in my original save (df-ai was installed, but disabled) and I had the same thing happen. It seemed to occur a few seasons after the unretire of a fortress - collapse on the surface, revealing and resetting every tile on the map. (This was a reset to pre-initial-embark, not pre-unretire, which I find really strange). This was a fort that I have been playing in for quite some time. df-ai had been used with this save before, but was disabled. open-legends has been correctly used with this save. I will check which other plugins I have enabled, but none of them seem particularly suspicious.

So, though whatever it is can apparently happen when df-ai is disabled, it happens reliably only when df-ai is enabled (If I make a new fortress and run in the background, I don't seem to reliably get this issue). Does df-ai do anything when it is installed but disabled? What other plugins does df-ai use that could be causing this issue when df-ai is disabled?

**Comment by lukebemish** [comment]
Looking around at versions - the newest df-ai release, which I was using, is for dfhack 0.47.04-r1, while I was using dfhack 0.47.04-r2. I will try to test on 0.47.04-r1 and on a fresh 0.47.04-r2 install to see if I can reproduce it there.

**Comment by lukebemish** [comment]
Huh, speaking of legends mode, this looks like it might be a `weblegends` issue; I can't reproduce it without `weblegends`, and I can reproduce it if `weblegends` is installed.

**Comment by lethosor** [comment]
It appears that weblegends does open a legends screen to generate region maps: https://github.com/BenLubar/weblegends/blob/ff6316171b11e008963d5f4c7e1bc00ac3397cde/map.cpp#L314

This appears to run if you view the region map (i.e. `region.png` - did you do this?) or possibly when you load a world. I'm not sure if this is capable of producing the same region corruption that `open-legends` ran into, but it seems like it could be a possible cause to me.

**Comment by lukebemish** [comment]
I think weblegends default starting screen contains a region map, but regardless, I was looking at site information for various sites in the world, which would use region.png. Seeing as I can't reproduce this issue without weblegends, and that opening legends from fortress is notoriously prone to corruption, I'd say that this is very likely the issue.

**Comment by Error916** [comment]
after some test i can confirm that weblegends is not the issue i start 5 different fortress without it and the bug pop out anyway. The only thing that is constant on all the saves who had this problem is the introduction of the ai in already start world. I can run the ai only for 5 hours so i save the world and start the next session the day after but every time this problem occurs

**Comment by BenLubar** [comment]
looks like the `zombie` flag was not the correct flag to use
