### ISSUE TITLE
version bump to work with LinuxLNP 0.43.03-r04 STABLE

### ISSUE THREAD

**Issue by neoice** [BenLubar/df-ai#8]
http://dffd.bay12games.com/file.php?id=11722

it's probably easier than updating the whole plugin to $latest. I'm not sure what they consider "stable", but I like the idea.

**Comment by neoice** [comment]
I compiled against dfhack at https://github.com/DFHack/dfhack/tree/0.43.03-r1

dfhack threw a warning on start, but it appears to be running df-ai without issue. it's been half an hour and it hasn't crashed yet :P

**Comment by lethosor** [comment]
What warning, specifically?

This plugin usually isn't hard to get working with new DFHack versions, especially in this case, since it had been compiled against 0.43.03-alpha1 before.

**Comment by neoice** [comment]
![screenshot_2017-04-07_10-34-09](https://cloud.githubusercontent.com/assets/71924/24812140/c9c1c58c-1b7d-11e7-811c-e34f401f7a54.png)

```
Warning: Plugin df-ai compiled for DFHack 0.43.03-r1-0-g98893793, running DFHack 0.43.03-r1-0-g9889379
```

g98893793 vs  g9889379 ...

so I need to step my `dfhack` back a few commits and recompile `df-ai`? or LNP needs to update their `dfhack`?

that final version number is meaningless to me.

**Comment by lethosor** [comment]
That's actually the same version, just truncated to a different number of digits. The exact commit is https://github.com/dfhack/dfhack/commit/98893793bd19d359b75771279d694bff7dd34ede (98893793bd19d359b75771279d694bff7dd34ede). I'm guessing your git version is different from the one used to compile DFHack (which was probably mine, between 2.10 and 2.12). That warning should be harmless, then.

**Comment by neoice** [comment]
```
% git --version
git version 2.11.0
```

if it's a non-issue, close it out. maybe someone else using the stable LNP will be helped by this thread :)
