### ISSUE TITLE
Map suddenly completely reveals, all dug out spaces filled back to their original blocks

### ISSUE THREAD

**Issue by Mukkuru2** [BenLubar/df-ai#83]
**Describe the bug**
The map fully revealed and all dug out spaces reverted to their original blocks.

**What happened**
The map fully revealed on two occasions on the same save, second time after quiting without saving. Then dwarves couldn't do anything anymore, cause most were stuck inside stone.

**Expected behavior**
Not suddenly doing this

**ai version:**

Dwarf Fortress 0.47.05
  Windows 64-bit
df-ai 0.47.05-r1-0-gd7302b4a
  code d7302b4a8ca9417b9d47337cf2009c0940c8f6e3
DFHack 0.47.05-r1-0-g032cd64c
  library 032cd64c10bf38fcb9d955c75a8ade4e857cc579
  structures 11c379ffd31255f2a1415d98106114a46245e1c3

[df-ai-debug.log](https://github.com/BenLubar/df-ai/files/6225034/df-ai-debug.log)

**Additional context**
I can provide a world download if you'd like me to, just tell me what scope of folders you'd like. I'll keep the world safe for now.

**Comment by Mukkuru2** [comment]
Happened on a personal playthrough too. Pretty sure this is a dfhack/df core issue

**Comment by lethosor** [comment]
Are you using `open-legends`?

**Comment by Mukkuru2** [comment]
> Are you using `open-legends`?

Yep. First time using it too.

**Comment by lethosor** [comment]
Ok, this is probably https://github.com/DFHack/dfhack/issues/1423 - there are known limitations to open-legends, which is why it includes a warning telling you to save before using it and quit after using it. Have you been doing that, or does this issue occur in the same DF session after using open-legends?
