### ISSUE TITLE
Cannot Enable plugin df-ai?

### ISSUE THREAD

**Issue by richardtheb** [BenLubar/df-ai#9]
Hey, I am using Peridexis Errants starter pack, which includes DFHack 0.43.03 and DF 0.43.03, which are, I think, the appropriate versions. I've copied the df-ai.plug.dll file into hack/plugins. 

 However, when I go into DFHAck and do "enable df-ai" I get the error of "cannot enable plugin df-ai". 

What am I missing here?

**Comment by lethosor** [comment]
There should be a suffix after the DFHack version, like "0.43.03-**r1**". If you got df-ai from the releases page in this repo ([here](https://github.com/BenLubar/df-ai/releases)), it looks like the most recent version there is for DFHack 0.43.03-alpha1. Plugins can't be used across different DFHack versions (DFHack will refuse to load them entirely).

By the way, you can check to see if a plugin is loaded with `plug` (or `plug df-ai` to narrow it down to just that plugin).

**Comment by richardtheb** [comment]
Ah, the version of DFHack is 0.43.03-r1. I'll try grabbing the alpha one. 

Oh, and plug df-ai responds with:

                     Name      State Cmds  Enabled
                    df-ai   unloaded    0      n/a

**Comment by richardtheb** [comment]
Yes, that Alpha version worked. My dwarves are now happily building away under AI control.

**Comment by lethosor** [comment]
It would be better to have a df-ai build for 0.43.03-r1 (@BenLubar would have to do that, though). It looks like most of the changes between 0.43.03-alpha1 and r1 were features, not bugfixes, but there's still a possibility that alpha1 will be more buggy.

**Comment by BenLubar** [comment]
@lethosor at your convenience, could you upload Mac OS builds of the two versions I just tagged?

https://github.com/BenLubar/df-ai/releases/tag/0.43.03-r1
https://github.com/BenLubar/df-ai/releases/tag/0.43.05-beta1

**Comment by lethosor** [comment]
Sure.
