### ISSUE TITLE
Steam version support

### ISSUE THREAD

**Issue by lavilao** [BenLubar/df-ai#94]
Hi, thanks for your work, are you going to add support for the steam version? thanks in advice!

**Comment by BenLubar** [comment]
Maybe, but probably not very soon. I've got a lot of things I'm already working on, and it's probably going to take a few months just to get DFHack working on Dwarf Fortress 0.50.xx

**Comment by lavilao** [comment]
Thanks for the fast answer! Dont worry, take your time I imagine that making an ai is not easy
